spring:
  profiles:
    include: shared
  application:
    name: ZIPKIN-SERVICE

armeria:
  enableMetrics: false

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka




