spring:
  profiles:
    include: shared
#  application:
#    name: ZIPKIN-SERVICE

armeria:
  enableMetrics: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.56.1:8761/eureka

#eureka:
#  instance:
#      preferIpAddress: true
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka




